[project]
name = "portfolio"
version = "0.2.0"
description = "A documentation website for past MITOS projects"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Yu Cheng", email = "yu_cheng@mit.edu" }
]
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material[imaging]>=9.5.40",
    "mkdocs-caption>=1.2.0",
    "mkdocs-git-revision-date-localized-plugin==1.2.9",
    "cairosvg>=2.7.1",
    "pillow>=10.4.0",
    "mkdocs-autolinks-plugin>=0.7.1",
]

[tool.uv]
package = false
