name: build-and-deploy 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.7
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      # - run: pip install mkdocs-material
      # - run: pip install pillow cairosvg
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
        with:
          version: 1.7.1  # Specify the Poetry version
      - name: Install dependencies
        run: poetry install
      - name: Deploy the site
        run: mkdocs gh-deploy --force